### ISSUE TITLE
效果链接 看不到啊

### ISSUE THREAD

**Issue by xiyouMc** [awolfly9/jd_analysis#1]

**Comment by awolfly9** [comment]
你说的是那个链接？用的是是浏览器打开，出现的错误是什么？

**Comment by xiyouMc** [comment]
@awolfly9 就是那几个预览的。  502  应该是服务器挂掉了吧

**Comment by awolfly9** [comment]
能不能说说你的访问条件，或者你加我下微信，测试反馈下。

**Comment by awolfly9** [comment]
@xiyouMc 现在可以看到效果链接了吗

**Comment by xiyouMc** [comment]
@awolfly9 看到了。 貌似 昨天的时候502 服务器挂掉了吧。 不过 可以加个微信。 毕竟都是Pythoneer. 
mcx1496
